### PR TITLE
Fixed CInv::IsKnownType()

### PR DESCRIPTION
**Pull request by CodeShark**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You should get rid of

```
bool operator<(const CInv& a, const CInv& b)
```

Either it is used somewhere, and just got broken by type's wit flag.
Either it is not, and it takes space for nothing.

**Comment by CodeShark** [comment]
Yes, PR #24 is the branch where we should do that.

**Comment by sipa** [comment]
Merged into segwit2. There is a warning to fix though:

```
21:04:54 < sipa> main.cpp:5063:103: warning: enumeral mismatch in conditional expression: ‘GetDataMsgWithFlags’ vs ‘GetDataMsg’ [-Wenum-compare]
21:04:54 < sipa>                      vGetData.push_back(CInv(State(pfrom->GetId())->fHaveWitness ? MSG_WITNESS_BLOCK : MSG_BLOCK, pindex->GetBlockHash()));
21:04:54 < sipa>                                                                                                        ^
```

**Comment by sipa** [comment]
@CodeShark Fix for the enum issue still welcome.

**Comment by CodeShark** [comment]
@sipa #29

**Pull request closed without merging**
