### PR TITLE
Rework BIP 9 warning system

### PR DESCRIPTION
**Pull request by morcos**

### CODE REVIEW

**Comment by sipa** [comment]
This seems more complicated than necessary to me.

How about mimicking VersionBitsConditionChecker, and have an equivalent VersionBitsCache, with one ThresholdConditionCache per bit, but one that is static and not recreating and repopulating the cache for every invocation?

**Comment by sdaftuar** [comment]
If the cache is static, then once you have warned on a bit once, you would never be able to warn for that bit again.  I think it seems safer if the warner always warned at the end of a period in which it appears that a BIP9-style activation may have occurred.

**Comment by sipa** [comment]
> If the cache is static, then once you have warned on a bit once, you
would never be able to warn for that bit again.

Why would you ever want to stop warning in this case?

-- 
Pieter

**Comment by sdaftuar** [comment]
I just think you'd want a way to distinguish between an alert for activity in an old period, versus an alert for activity that is happening in the current/most recent period.

Otherwise, if you ever got a spurious alert -- say miners in one time period are using version numbers to signal something else, such that enough blocks were to go by that looked like something triggered but is a false alarm -- then the alert system is no longer useful for that bit, because you can't distinguish future alerts from the previously reported false alarm.

**Comment by morcos** [comment]
I don't really have a strong opinion about doing it exactly this way.. It just seemed a tad wasteful to use 300K or so to keep caches which actually contain no information since as @sdaftuar points out what you really want is to check every period and see whether something could have locked in and not depend on the full state machine logic.

The important thing is that we are A) looking for soft fork activations all the time (including during IBD) and B) have a more sensitive warning for ongoing nVersions that we don't understand.

**Comment by sipa** [comment]
@morcos By "more sensitive" in B, you mean something that triggers at lower thresholds?

**Comment by morcos** [comment]
Yes I meant that the old code warned when it saw literally any blocks it didn't understand and alerted when > 50/100.  I don't see any reason why we don't want this same information now.  So basically I'm suggesting we keep that, and add special tracking for unknown BIP 9 activations (A)

**Comment by sipa** [comment]
I've reworked the code in #7575 using a different approach. I kept the 50/100 check, but also made the versionbits warning check track per bit. Maybe it's overkill, but I don't think it's relevant to be able to find multiple unknown deployments of the same bit.

**Pull request closed without merging**
