### PR TITLE
Make v2-v16 witness program non-standard

### PR DESCRIPTION
**Pull request by jl2012**

### CODE REVIEW

**Comment by sipa** [comment]
They already are, no? Due to the CLEANSTACK rule.

**Comment by sipa** [comment]
Never mind, still half asleep.

We nesd this indeed.

**Comment by jl2012** [comment]
It's possible to mine a v3 program with garbage witness: 938a034a96f862635b19c76eb0694746c0374fda508df01d2265fceb2bf97350

**Comment by sipa** [comment]
Cherry-picked into my branch.

**Pull request closed without merging**
