### PR TITLE
segwit: gui wallet send transaction size calculation assertion failed

### PR DESCRIPTION
**Pull request by mruddy**
I noticed a failed assertion when trying to send with the GUI wallet.
Here's a quick fix that stops the assertion. Not sure if it's how you want to handle it. But at least this can serve as a place holder to remember to fix this.
Assertion info below:

> bitcoin-qt: ./primitives/transaction.h:289: void SerializeTransaction(TxType&, Stream&, Operation, int, int) [with Stream = CSizeComputer; Operation = CSerActionSerialize; TxType = CTransaction]: Assertion `!(nVersion & SERIALIZE_TRANSACTION_WITNESS) ^ !(nVersion & SERIALIZE_TRANSACTION_NO_WITNESS)' failed.

Call stack when the assertion failed:
image

The send dialog I used to cause the failure (nothing special really):
image

### CODE REVIEW

**Comment by jonasschnelli** [comment]
IMO this PR is required before SW can be merged.

Tested ACK.

**Comment by mruddy** [comment]
@jonasschnelli thanks for testing. I was just wondering, since there hasn't been any other feedback, is this the right place to propose this fix? Or are segwit updates being batched on some schedule etc...?

**Comment by sipa** [comment]
@mruddy Yes, this is the right place. I process the comments to the segwit
branch in batches.

**Comment by mruddy** [comment]
@sipa excellent, thank-you!

**Comment by sipa** [comment]
I think this should use GetVirtualTransactionSize instead.

**Comment by mruddy** [comment]
I've made the update to use GetVirtualTransactionSize. I also made some related updates to the coin control logic for transactions with witness data. I don't really like the inexactness of the results, but I guess they're acceptable as estimates. I tried to keep the set of changes small while still producing reasonable output. Seems kind of kludgy. You'll probably think of a better way to handle it :) Here's at least an idea.

**Comment by sipa** [comment]
Including in next batch.

**Comment by mruddy** [comment]
merged, closing, thanks

**Pull request closed without merging**
