### PR TITLE
signrawtransaction can sign P2WSH

### PR DESCRIPTION
**Pull request by NicolasDorier**
@sdaftuar might be useful for your tests

### CODE REVIEW

**Comment by fivepiece** [comment]
`segnet-cli signrawtransaction 010000000100010000000000000000000000000000000000000000000000000000000000000000000000ffffffff01e8030000000000001976a9144c9c3dfac4207d5d8cb89df5722cb3d712385e3f88ac00000000 '[{"txid":"0000000000000000000000000000000000000000000000000000000000000100","vout":0,"scriptPubKey":"0020ff25429251b5a84f452230a3c75fd886b7fc5a7865ce4a7bb7a9d7c5be6da3db","redeemScript":"2103596d3451025c19dbbdeb932d6bf8bfb4ad499b95b6f88db8899efac102e5fc71ac","amount":0.00001000}]' '["QWZL3KqGUNZ5WQGgw5b6ui14VGv7NAbZvroCjUB8ucVVnZZ5T1uZ"]'``

works now, though the same using `bitcoin-tx` still doesn't

**Comment by fivepiece** [comment]
Replacing `./src/bitcoin-tx.cpp:448` to:

`if (fGivenKeys && ( scriptPubKey.IsPayToScriptHash() || scriptPubKey.IsPayToWitnessScriptHash() ) &&`

Makes it work!

**Comment by NicolasDorier** [comment]
awesome thanks a lot for you testing, I updated the PR

**Comment by sipa** [comment]
Cherry-picked into segwit4.

**Pull request closed without merging**
